spring.application.name=springweb

# day04_0902
# 주석 : .properties 파일의 주석 방법
# application.properties 파일이란? spring 관련 설정 코드 입력하는 곳
# 1. 내장 톰캣의 포트 번호 변경, 기본값 8080
server.port = 8080
# 2. 데이터베이스 연동
# 2-1 : 연동할 DB 주소
spring.datasource.url = jdbc:mysql://localhost:3306/mydb0903
# 2-2: DB 주소의 계정명/비밀번호
spring.datasource.username=root
spring.datasource.password=1234

# day05
# 3.  DDL :
# create : 서버 실행될 때 엔티티 기반으로 테이블 삭제 -> 생성
# create-drop : 서버 실행될 때 엔티티 기반으로 테이블 생성, 서버 종료시 삭제
# update : 서버가 실행될 때 존재하면 엔티티 수정, 없으면 생성
# none : 사용안함  
spring.jpa.hibernate.ddl-auto = create-drop
# 4. SQL 콘솔 출력
spring.jpa.show-sql=true
#콘솔에 출력되는 SQL 줄바꿈 및 들여쓰기 적용 (가독성 향상) , 개발단계에서는 쓰고 배포에서 지운다
spring.jpa.properties.hibernate.format_sql=true

