spring.application.name=springweb

# day04_0902
# 주석 : .properties 파일의 주석 방법
# application.properties 파일이란? spring 관련 설정 코드 입력하는 곳
# 1. 내장 톰캣의 포트 번호 변경, 기본값 8080
server.port = 8080
# 2. 데이터베이스 연동
# 2-1 : 연동할 DB 주소
spring.datasource.url = jdbc:mysql://localhost:3306/mydb0903
# 2-2: DB 주소의 계정명/비밀번호
spring.datasource.username=root
spring.datasource.password=1234

# day05
# 3.  DDL :
# create : 서버 실행될 때 엔티티 기반으로 테이블 삭제 -> 생성
# create-drop : 서버 실행될 때 엔티티 기반으로 테이블 생성, 서버 종료시 삭제
# update : 서버가 실행될 때 존재하면 엔티티 수정, 없으면 생성
# none : 사용안함  
spring.jpa.hibernate.ddl-auto = create
# 4. SQL 콘솔 출력
spring.jpa.show-sql=true
#콘솔에 출력되는 SQL 줄바꿈 및 들여쓰기 적용 (가독성 향상) , 개발단계에서는 쓰고 배포에서 지운다
spring.jpa.properties.hibernate.format_sql=true

# 5 서버 실행 할때 SQL 파일 실행 *개발단계* , always,none *운영/배포 단계 사용하지 않는다*
 spring.sql.init.mode = always
# # 6 서버 실행 할때 classpath(resources폴더) 이하 에 data.sql 파일 경로 지정
 spring.sql.init.data-locations=classpath:/sql/0903.sql
# # 7 서버 실행 할때 JPA가 초기화 파일 실행
 spring.jpa.defer-datasource-initialization = true
# # 한글 지원 코드
 spring.sql.init.encoding=UTF-8